services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Hong_Kong
      DB_HOST:
      DB_USER:
      DB_PASSWORD: ''
      DB_NAME:
      TITLE_SUFFIX:
    restart: unless-stopped
